In [37]:
import tensorflow as tf
import numpy as np
import os
import sys
BASE_DIR = os.path.dirname(os.path.abspath('train_scannet_IoU.py'))
sys.path.append(BASE_DIR)
sys.path.append(os.path.join(BASE_DIR, 'utils'))
import pointconv_util

In [31]:
w = tf.Variable([[0.4, 1.2,2,2,2]], dtype=tf.float32) # w.shape: [2, 1]
x = tf.Variable([[1,2,2,2,2], [1,2,2,2,2]], dtype=tf.float32) # x.shape: [2, 5]
y =  x*w     # 等同于 y = tf.multiply(w, x)   y.shape: [2, 5]

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print (sess.run(w))
print (sess.run(x))
print (sess.run(y))

[[0.4 1.2 2.  2.  2. ]]
[[1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]]
[[0.4 2.4 4.  4.  4. ]
 [0.4 2.4 4.  4.  4. ]]


In [38]:
sys.path.append('../')
from generateDataSet import dataArgumentation

In [40]:
filenames = ['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19']
test_points_r, test_labels_r = dataArgumentation.get_trainSetwithLabel(filenames, 1024, 1)

In [42]:
test_points_r.shape

(20, 1024, 3)

In [44]:
new_xyz1 = pointconv_util.sampling(10,test_points_r)

In [45]:
new_xyz2 = pointconv_util.sampling(10,test_points_r)

In [47]:
test = new_xyz1 - new_xyz1

In [48]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print (sess.run(test))


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.